Repository cdnjs/cdnjs, pull requests merged in 2018-12, with the labels that each got.

#13107 Update badges in readme
  README.md
Labels: in progress

#13018 [Author] [New] Add scribbletune w/ npm auto-update via single package.json
  ajax/libs/scribbletune/package.json
Labels: in progress

#13113 Update svg.js to use npm auto-update
  ajax/libs/svg.js/3.0.3/polyfills.js
  ajax/libs/svg.js/3.0.3/polyfillsIE.js
  ajax/libs/svg.js/3.0.3/svg.js
  ajax/libs/svg.js/3.0.3/svg.js.map
  ajax/libs/svg.js/3.0.3/svg.min.js
  ajax/libs/svg.js/3.0.3/svg.min.js.map
  ajax/libs/svg.js/package.json
Labels: in progress

#12923 [New] Add ng-bootstrap@3.0.0 w/ npm auto-update
  ajax/libs/ng-bootstrap/3.0.0/ng-bootstrap.umd.js
  ajax/libs/ng-bootstrap/3.0.0/ng-bootstrap.umd.js.map
  ajax/libs/ng-bootstrap/3.0.0/ng-bootstrap.umd.min.js
  ajax/libs/ng-bootstrap/3.0.0/ng-bootstrap.umd.min.js.map
  ajax/libs/ng-bootstrap/package.json
Labels: :rotating_light: High Priority, in progress

#13037 [new] Add rxdb w/ npm auto-update via single package.json
  ajax/libs/rxdb/package.json
Labels: :rotating_light: High Priority, in progress

#12933 [New] Add webkul-micron w/ npm auto-update via single package.json
  ajax/libs/webkul-micron/package.json
Labels: in progress

#13041 [new] Add vivid w/ npm auto-update via single package.json
  ajax/libs/vivid/package.json
Labels: in progress

#12811 [New] Add san@3.6.0 w/ npm auto-update
  ajax/libs/san/3.6.0/san.dev.js
  ajax/libs/san/3.6.0/san.js
  ajax/libs/san/3.6.0/san.min.js
  ajax/libs/san/3.6.0/san.modern.dev.js
  ajax/libs/san/3.6.0/san.modern.js
  ajax/libs/san/3.6.0/san.modern.min.js
  ajax/libs/san/3.6.0/san.spa.dev.js
  ajax/libs/san/3.6.0/san.spa.js
  ajax/libs/san/3.6.0/san.spa.min.js
  ajax/libs/san/3.6.0/san.spa.modern.dev.js
  ajax/libs/san/3.6.0/san.spa.modern.js
  ajax/libs/san/3.6.0/san.spa.modern.min.js
  ajax/libs/san/3.6.0/san.ssr.js
  ajax/libs/san/package.json
Labels: :rotating_light: High Priority, in progress

#12913 Update react-move auto-update/metadata & add missing versions
  ajax/libs/react-move/2.0.0/react-move.js
  ajax/libs/react-move/2.0.0/react-move.min.js
  ajax/libs/react-move/2.1.0/react-move.js
  ajax/libs/react-move/2.1.0/react-move.min.js
  ajax/libs/react-move/2.2.0/react-move.js
  ajax/libs/react-move/2.2.0/react-move.min.js
  ajax/libs/react-move/2.3.0/react-move.js
  ajax/libs/react-move/2.3.0/react-move.min.js
  ajax/libs/react-move/2.4.0/react-move.js
  ajax/libs/react-move/2.4.0/react-move.min.js
  ajax/libs/react-move/2.5.0/react-move.js
  ajax/libs/react-move/2.5.0/react-move.min.js
  ajax/libs/react-move/2.5.1/react-move.js
  ajax/libs/react-move/2.5.1/react-move.min.js
  ajax/libs/react-move/2.6.0/react-move.js
  ajax/libs/react-move/2.6.0/react-move.min.js
  ajax/libs/react-move/2.7.0/react-move.js
  ajax/libs/react-move/2.7.0/react-move.min.js
  ajax/libs/react-move/2.8.0/react-move.js
  ajax/libs/react-move/2.8.0/react-move.min.js
  ajax/libs/react-move/package.json
Labels: :rotating_light: High Priority, in progress

#13156 Update jquery.mb.YTPlayer license info in package.json
  ajax/libs/jquery.mb.YTPlayer/package.json
Labels: in progress

#13155 Update jquery.collapsible license info in package.json
  ajax/libs/jquery.collapsible/package.json
Labels: in progress

#11248 Add modestmaps@3.3.5 w/ npm auto-update
  ajax/libs/modestmaps/3.3.5/modestmaps.js
  ajax/libs/modestmaps/3.3.5/modestmaps.min.js
  ajax/libs/modestmaps/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress

#13157 Add nes.css w/ npm auto-update via single package.json
  ajax/libs/nes.css/0.0.1/css/nes.css
  ajax/libs/nes.css/0.0.1/css/nes.css.map
  ajax/libs/nes.css/0.0.1/css/nes.min.css
  ajax/libs/nes.css/0.0.2/css/nes.css
  ajax/libs/nes.css/0.0.2/css/nes.css.map
  ajax/libs/nes.css/0.0.2/css/nes.min.css
  ajax/libs/nes.css/1.0.0/css/nes.css
  ajax/libs/nes.css/1.0.0/css/nes.css.map
  ajax/libs/nes.css/1.0.0/css/nes.min.css
  ajax/libs/nes.css/package.json
Labels: in progress
