Repository cdnjs/cdnjs, pull requests merged in 2018-02, with the labels that each got.

#12467 [New] Add focusable w/ git auto-update via single package.json
  ajax/libs/focusable/package.json
Labels: High Priority, in progress

#12222 [New] Add open-weather@1.2.0 w/ git auto-update
  ajax/libs/open-weather/1.2.0/openWeather.js
  ajax/libs/open-weather/1.2.0/openWeather.min.js
  ajax/libs/open-weather/package.json
Labels: in progress

#12219 [New] Add jquery-teletype-plugin@0.1.6 w/ git auto-update
  ajax/libs/jquery-teletype-plugin/0.1.6/jquery.teletype.js
  ajax/libs/jquery-teletype-plugin/0.1.6/jquery.teletype.min.js
  ajax/libs/jquery-teletype-plugin/package.json
Labels: in progress

#12446 [New] Add frappe-gantt@0.0.7 w/ npm auto-update
  ajax/libs/frappe-gantt/0.0.7/frappe-gantt.js
  ajax/libs/frappe-gantt/0.0.7/frappe-gantt.js.map
  ajax/libs/frappe-gantt/0.0.7/frappe-gantt.min.js
  ajax/libs/frappe-gantt/0.0.7/frappe-gantt.min.js.map
  ajax/libs/frappe-gantt/package.json
Labels: in progress, in progress 🚧

#12522 [New] Add collect.js@4.0.11 w/ git auto-update
  ajax/libs/collect.js/4.0.11/collect.js
  ajax/libs/collect.js/4.0.11/collect.min.js
  ajax/libs/collect.js/package.json
Labels: High Priority, in progress, in progress 🚧

#12286 [New] Add fullcalendar-scheduler@1.9.0 w/ git auto-update
  ajax/libs/fullcalendar-scheduler/1.9.0/scheduler.css
  ajax/libs/fullcalendar-scheduler/1.9.0/scheduler.js
  ajax/libs/fullcalendar-scheduler/1.9.0/scheduler.min.css
  ajax/libs/fullcalendar-scheduler/1.9.0/scheduler.min.js
  ajax/libs/fullcalendar-scheduler/package.json
Labels: in progress 🚧

#12472 [New] Add react-sortable-hoc@0.6.8 w/ npm auto-update
  ajax/libs/react-sortable-hoc/0.6.8/react-sortable-hoc.js
  ajax/libs/react-sortable-hoc/0.6.8/react-sortable-hoc.min.js
  ajax/libs/react-sortable-hoc/0.6.8/react-sortable-hoc.min.js.map
  ajax/libs/react-sortable-hoc/package.json
Labels: High Priority, in progress 🚧

#12490 [New] Add jsnes w/ npm auto-update via single package.json
  ajax/libs/jsnes/package.json
Labels: in progress 🚧

#12255 [New] Add iNotify@1.0.14 w/ git auto-update
  ajax/libs/iNotify/1.0.14/iNotify.js
  ajax/libs/iNotify/1.0.14/iNotify.min.js
  ajax/libs/iNotify/package.json
Labels: in progress

#12254 [New] Add progressStep@1.0.3 w/ git auto-update
  ajax/libs/progressStep/1.0.3/progressStep.js
  ajax/libs/progressStep/1.0.3/progressStep.min.js
  ajax/libs/progressStep/package.json
Labels: in progress
