Repository cdnjs/cdnjs, pull requests merged in 2018-04, with the labels that each got.

#12143 [New] Add angular-growl@0.4.0 w/ git auto-update
  ajax/libs/angular-growl/0.4.0/angular-growl.js
  ajax/libs/angular-growl/0.4.0/angular-growl.min.css
  ajax/libs/angular-growl/0.4.0/angular-growl.min.js
  ajax/libs/angular-growl/package.json
Labels: in progress

#12087 [New] Add jquery-loading-overlay w/ git auto-update
  ajax/libs/jquery-loading-overlay/1.0/loading.gif
  ajax/libs/jquery-loading-overlay/1.0/loadingoverlay.js
  ajax/libs/jquery-loading-overlay/1.0/loadingoverlay.min.js
  ajax/libs/jquery-loading-overlay/1.1/loading.gif
  ajax/libs/jquery-loading-overlay/1.1/loadingoverlay.js
  ajax/libs/jquery-loading-overlay/1.1/loadingoverlay.min.js
  ajax/libs/jquery-loading-overlay/1.2/loading.gif
  ajax/libs/jquery-loading-overlay/1.2/loadingoverlay.js
  ajax/libs/jquery-loading-overlay/1.2/loadingoverlay.min.js
  ajax/libs/jquery-loading-overlay/1.2/loadingoverlay_progress.js
  ajax/libs/jquery-loading-overlay/1.2/loadingoverlay_progress.min.js
  ajax/libs/jquery-loading-overlay/1.3/loading.gif
  ajax/libs/jquery-loading-overlay/1.3/loadingoverlay.js
  ajax/libs/jquery-loading-overlay/1.3/loadingoverlay.min.js
  ajax/libs/jquery-loading-overlay/1.3/loadingoverlay_progress.js
  ajax/libs/jquery-loading-overlay/1.3/loadingoverlay_progress.min.js
  ajax/libs/jquery-loading-overlay/1.5.4/loadingoverlay.js
  ajax/libs/jquery-loading-overlay/1.5.4/loadingoverlay.min.js
  ajax/libs/jquery-loading-overlay/1.5.4/loadingoverlay_progress.js
  ajax/libs/jquery-loading-overlay/1.5.4/loadingoverlay_progress.min.js
  ajax/libs/jquery-loading-overlay/package.json
Labels: in progress

#12170 Update Snowstorm license info in package.json
  ajax/libs/Snowstorm/package.json
Labels: in progress

#12249 Add androidicons@1.0 w/ git auto-update
  ajax/libs/androidicons/1.0/css/androidicons.css
  ajax/libs/androidicons/1.0/css/androidicons.min.css
  ajax/libs/androidicons/1.0/css/androidicons.min.css.map
  ajax/libs/androidicons/1.0/font/androidicons.eot
  ajax/libs/androidicons/1.0/font/androidicons.svg
  ajax/libs/androidicons/1.0/font/androidicons.ttf
  ajax/libs/androidicons/1.0/font/androidicons.woff
  ajax/libs/androidicons/package.json
Labels: in progress

#12684 [New] Add Blotter@0.1.0 w/ git auto-update
  ajax/libs/Blotter/0.1.0/blotter.js
  ajax/libs/Blotter/0.1.0/blotter.min.js
  ajax/libs/Blotter/0.1.0/materials/channelSplitMaterial.js
  ajax/libs/Blotter/0.1.0/materials/fliesMaterial.js
  ajax/libs/Blotter/0.1.0/materials/liquidDistortMaterial.js
  ajax/libs/Blotter/0.1.0/materials/rollingDistortMaterial.js
  ajax/libs/Blotter/0.1.0/materials/slidingDoorMaterial.js
  ajax/libs/Blotter/package.json
Labels: :rotating_light: High Priority, in progress

#12164 Update jquery.tablesorter license in package.json
  ajax/libs/jquery.tablesorter/package.json
Labels: :warning: PR wait for fixing, in progress

#12526 [New] Add multi-level-push-menu w/ git auto-update via single package.json
  ajax/libs/multi-level-push-menu/package.json
Labels: in progress

#12419 Add jeditable.js@1.8.0 w/ git auto-update & update package.json
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.ajaxupload.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.ajaxupload.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.autogrow.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.autogrow.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.charcounter.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.charcounter.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.datepicker.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.datepicker.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.masked.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.masked.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.time.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.time.min.js
  ajax/libs/jeditable.js/1.8.0/jquery.jeditable.timepicker.min.js
  ajax/libs/jeditable.js/package.json
Labels: :rotating_light: High Priority, in progress

#12154 [New] Add PrintArea@2.4.1 w/ git auto-update
  ajax/libs/PrintArea/2.4.1/PrintArea.css
  ajax/libs/PrintArea/2.4.1/PrintArea.min.css
  ajax/libs/PrintArea/2.4.1/PrintArea.min.css.map
  ajax/libs/PrintArea/2.4.1/jquery.PrintArea.js
  ajax/libs/PrintArea/2.4.1/jquery.PrintArea.min.js
  ajax/libs/PrintArea/2.4.1/jquery.PrintArea.min.js.map
  ajax/libs/PrintArea/package.json
Labels: in progress

#12173 [New] Add PickMeUp@3.0.11 w/ git auto-update
  ajax/libs/PickMeUp/3.1.3/css/pickmeup.css
  ajax/libs/PickMeUp/3.1.3/js/jquery.pickmeup.twitter-bootstrap.js
  ajax/libs/PickMeUp/3.1.3/js/jquery.pickmeup.twitter-bootstrap.min.js
  ajax/libs/PickMeUp/3.1.3/js/jquery.pickmeup.uikit.js
  ajax/libs/PickMeUp/3.1.3/js/jquery.pickmeup.uikit.min.js
  ajax/libs/PickMeUp/3.1.3/js/pickmeup.js
  ajax/libs/PickMeUp/3.1.3/pickmeup.min.js
  ajax/libs/PickMeUp/package.json
Labels: in progress

#12191 [New] Add reframe.js@2.1.18 w/ npm auto-update
  ajax/libs/reframe.js/0.0.1/responsive-iframe.css
  ajax/libs/reframe.js/0.0.1/responsive-iframe.js
  ajax/libs/reframe.js/2.1.18/jquery.noframe.js
  ajax/libs/reframe.js/2.1.18/jquery.noframe.min.js
  ajax/libs/reframe.js/2.1.18/jquery.reframe.js
  ajax/libs/reframe.js/2.1.18/jquery.reframe.min.js
  ajax/libs/reframe.js/2.1.18/noframe.js
  ajax/libs/reframe.js/2.1.18/noframe.min.js
  ajax/libs/reframe.js/2.1.18/reframe.js
  ajax/libs/reframe.js/2.1.18/reframe.min.js
  ajax/libs/reframe.js/package.json
Labels: in progress

#12730 Update Primer auto-update & metadata
  ajax/libs/Primer/package.json
Labels: :rotating_light: High Priority, in progress

#12729 Update Sweetalert auto-update config, homepage & keywords
  ajax/libs/sweetalert/package.json
Labels: :rotating_light: High Priority, in progress

#12072 Transfer alertify.js to git auto-update, add v0.4.0rc1
  ajax/libs/alertify.js/0.4.0rc1/alertify.js
  ajax/libs/alertify.js/0.4.0rc1/alertify.min.js
  ajax/libs/alertify.js/0.4.0rc1/themes/alertify.bootstrap.css
  ajax/libs/alertify.js/0.4.0rc1/themes/alertify.bootstrap.min.css
  ajax/libs/alertify.js/0.4.0rc1/themes/alertify.css
  ajax/libs/alertify.js/0.4.0rc1/themes/alertify.default.css
  ajax/libs/alertify.js/0.4.0rc1/themes/alertify.default.min.css
  ajax/libs/alertify.js/0.4.0rc1/themes/alertify.min.css
  ajax/libs/alertify.js/package.json
Labels: :rotating_light: High Priority, in progress

#11828 [New] Add loadCSS w/ git auto-update via single package.json
  .gitignore
  ajax/libs/loadCSS/1.1.0/cssrelpreload.js
  ajax/libs/loadCSS/1.1.0/cssrelpreload.min.js
  ajax/libs/loadCSS/1.1.0/loadCSS.js
  ajax/libs/loadCSS/1.1.0/loadCSS.min.js
  ajax/libs/loadCSS/1.1.0/onloadCSS.js
  ajax/libs/loadCSS/1.1.0/onloadCSS.min.js
  ajax/libs/loadCSS/package.json
Labels: in progress
