Repository cdnjs/cdnjs, pull requests merged in 2018-06, with the labels that each got.

#12768 [New] Add dayjs@1.5.24 w/ npm auto-update
  ajax/libs/dayjs/1.5.24/dayjs.min.js
  ajax/libs/dayjs/package.json
Labels: :rotating_light: High Priority, in progress

#12095 [New] Add firmin@1.0.0 w/ git auto-update
  ajax/libs/firmin/1.0.0/firmin.js
  ajax/libs/firmin/1.0.0/firmin.min.js
  ajax/libs/firmin/package.json
Labels: in progress

#12805 Update .gitignore for v-mask incompatible versions
  .gitignore
Labels: in progress

#12806 Update simple-jekyll-search autoupdate config
  ajax/libs/simple-jekyll-search/1.7.0/simple-jekyll-search.js
  ajax/libs/simple-jekyll-search/1.7.0/simple-jekyll-search.min.js
  ajax/libs/simple-jekyll-search/package.json
Labels: in progress

#12721 [New] Add driver.js@0.5.0 w/ npm auto-update
  ajax/libs/driver.js/0.5.0/driver.min.css
  ajax/libs/driver.js/0.5.0/driver.min.css.map
  ajax/libs/driver.js/0.5.0/driver.min.js
  ajax/libs/driver.js/0.5.0/driver.min.js.map
  ajax/libs/driver.js/package.json
Labels: :rotating_light: High Priority, in progress

#12076 [New] Add imgcache.js w/ git auto-update
  ajax/libs/imgcache.js/0.7.0/imgcache.js
  ajax/libs/imgcache.js/0.7.0/imgcache.min.js
  ajax/libs/imgcache.js/0.7.0/imgcache.min.js.map
  ajax/libs/imgcache.js/0.7.1/imgcache.js
  ajax/libs/imgcache.js/0.7.1/imgcache.min.js
  ajax/libs/imgcache.js/0.7.1/imgcache.min.js.map
  ajax/libs/imgcache.js/0.7.2/imgcache.js
  ajax/libs/imgcache.js/0.7.2/imgcache.min.js
  ajax/libs/imgcache.js/0.7.2/imgcache.min.js.map
  ajax/libs/imgcache.js/0.7.3/imgcache.js
  ajax/libs/imgcache.js/0.7.3/imgcache.min.js
  ajax/libs/imgcache.js/0.7.3/imgcache.min.js.map
  ajax/libs/imgcache.js/0.7.4/imgcache.js
  ajax/libs/imgcache.js/0.7.4/imgcache.min.js
  ajax/libs/imgcache.js/0.7.4/imgcache.min.js.map
  ajax/libs/imgcache.js/0.7.5/imgcache.js
  ajax/libs/imgcache.js/0.7.5/imgcache.min.js
  ajax/libs/imgcache.js/0.7.5/imgcache.min.js.map
  ajax/libs/imgcache.js/0.7.6/imgcache.js
  ajax/libs/imgcache.js/0.7.6/imgcache.min.js
  ajax/libs/imgcache.js/0.7.6/imgcache.min.js.map
  ajax/libs/imgcache.js/1.0.0/imgcache.js
  ajax/libs/imgcache.js/1.0.0/imgcache.min.js
  ajax/libs/imgcache.js/1.0.0/imgcache.min.js.map
  ajax/libs/imgcache.js/1.0.0/qimgcache.js
  ajax/libs/imgcache.js/1.0.0/qimgcache.min.js
  ajax/libs/imgcache.js/1.0.0/qimgcache.min.js.map
  ajax/libs/imgcache.js/1.0rc1/imgcache.js
  ajax/libs/imgcache.js/1.0rc1/imgcache.min.js
  ajax/libs/imgcache.js/1.0rc1/imgcache.min.js.map
  ajax/libs/imgcache.js/1.0rc1/qimgcache.js
  ajax/libs/imgcache.js/1.0rc1/qimgcache.min.js
  ajax/libs/imgcache.js/1.0rc1/qimgcache.min.js.map
  ajax/libs/imgcache.js/1.0rc2/imgcache.js
  ajax/libs/imgcache.js/1.0rc2/imgcache.min.js
  ajax/libs/imgcache.js/1.0rc2/imgcache.min.js.map
  ajax/libs/imgcache.js/1.0rc2/qimgcache.js
  ajax/libs/imgcache.js/1.0rc2/qimgcache.min.js
  ajax/libs/imgcache.js/1.0rc2/qimgcache.min.js.map
  ajax/libs/imgcache.js/1.1.0/imgcache.js
  ajax/libs/imgcache.js/1.1.0/imgcache.min.js
  ajax/libs/imgcache.js/1.1.0/imgcache.min.js.map
  ajax/libs/imgcache.js/1.1.0/qimgcache.js
  ajax/libs/imgcache.js/1.1.0/qimgcache.min.js
  ajax/libs/imgcache.js/1.1.0/qimgcache.min.js.map
  ajax/libs/imgcache.js/1.2.0/imgcache.js
  ajax/libs/imgcache.js/1.2.0/imgcache.min.js
  ajax/libs/imgcache.js/1.2.0/imgcache.min.js.map
  ajax/libs/imgcache.js/1.2.0/qimgcache.js
  ajax/libs/imgcache.js/1.2.0/qimgcache.min.js
  ajax/libs/imgcache.js/1.2.0/qimgcache.min.js.map
  ajax/libs/imgcache.js/2.0.0/imgcache-promise.js
  ajax/libs/imgcache.js/2.0.0/imgcache-promise.min.js
  ajax/libs/imgcache.js/2.0.0/imgcache-promise.min.js.map
  ajax/libs/imgcache.js/2.0.0/imgcache.js
  ajax/libs/imgcache.js/2.0.0/imgcache.min.js
  ajax/libs/imgcache.js/2.0.0/imgcache.min.js.map
  ajax/libs/imgcache.js/package.json
Labels: in progress

#12342 Add tweenjs missing versions & change filenames in some versions
  ajax/libs/tweenjs/0.1.0/tweenjs.min.js
  ajax/libs/tweenjs/0.2.0/tweenjs.min.js
  ajax/libs/tweenjs/0.3.0/tweenjs.min.js
  ajax/libs/tweenjs/0.4.1/tweenjs.min.js
  ajax/libs/tweenjs/1.0.0/tweenjs.js
  ajax/libs/tweenjs/1.0.0/tweenjs.min.js
Labels: :warning: PR wait for fixing, in progress

#11847 Add multiple licenses and update multiple git repository of libs in one commit
  ajax/libs/DinaKit/package.json
  ajax/libs/across-tabs/package.json
  ajax/libs/documentup/package.json
  ajax/libs/entypo/package.json
  ajax/libs/expect.js/package.json
  ajax/libs/foundicons/package.json
  ajax/libs/jquery-parallax/package.json
  ajax/libs/jquery-sparklines/package.json
  ajax/libs/jquery.formalize/package.json
  ajax/libs/jquery.lifestream/package.json
  ajax/libs/jquery.postcodify/package.json
  ajax/libs/jquery.selectboxit/package.json
  ajax/libs/jquery.socialshareprivacy/package.json
  ajax/libs/linq.js/package.json
  ajax/libs/log4javascript/package.json
  ajax/libs/meyer-reset/package.json
  ajax/libs/prettydiff/package.json
  ajax/libs/prototype/package.json
  ajax/libs/require-cs/package.json
  ajax/libs/require-jquery/package.json
  ajax/libs/salesforce-canvas/package.json
  ajax/libs/skel-layers/package.json
  ajax/libs/slabText/package.json
  ajax/libs/thorax/package.json
Labels: in progress

#12035 Add expect.js@0.3.1 w/ git auto-update & update package.json
  ajax/libs/expect.js/0.3.1/index.js
  ajax/libs/expect.js/0.3.1/index.min.js
  ajax/libs/expect.js/package.json
Labels: in progress

#12039 [New] Add videojs-thumbnails@0.1.1 w/ git auto-update
  ajax/libs/videojs-thumbnails/0.1.1/videojs.thumbnails.css
  ajax/libs/videojs-thumbnails/0.1.1/videojs.thumbnails.js
  ajax/libs/videojs-thumbnails/0.1.1/videojs.thumbnails.min.css
  ajax/libs/videojs-thumbnails/0.1.1/videojs.thumbnails.min.css.map
  ajax/libs/videojs-thumbnails/0.1.1/videojs.thumbnails.min.js
  ajax/libs/videojs-thumbnails/0.1.1/videojs.thumbnails.min.js.map
  ajax/libs/videojs-thumbnails/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress

#12506 [author] [new] adding new pnp scoped client side libraries
  ajax/libs/pnp-common/package.json
  ajax/libs/pnp-config-store/package.json
  ajax/libs/pnp-graph/package.json
  ajax/libs/pnp-logging/package.json
  ajax/libs/pnp-odata/package.json
  ajax/libs/pnp-pnpjs/package.json
  ajax/libs/pnp-sp-addinhelpers/package.json
  ajax/libs/pnp-sp-clientsvc/package.json
  ajax/libs/pnp-sp-taxonomy/package.json
  ajax/libs/pnp-sp/package.json
Labels: in progress

#12809 Add missing png files and homepage info of jquery.nicescroll
  ajax/libs/jquery.nicescroll/3.5.1/zoomico.png
  ajax/libs/jquery.nicescroll/3.5.4/zoomico.png
  ajax/libs/jquery.nicescroll/3.5.6/zoomico.png
  ajax/libs/jquery.nicescroll/3.6.0/zoomico.png
  ajax/libs/jquery.nicescroll/package.json
Labels: :rotating_light: High Priority, in progress

#11876 [New] Add image-select@2.0 w/ git auto-update
  ajax/libs/image-select/1.3/ImageSelect.css
  ajax/libs/image-select/1.3/ImageSelect.jquery.js
  ajax/libs/image-select/1.3/ImageSelect.jquery.min.js
  ajax/libs/image-select/1.3/ImageSelect.jquery.min.js.map
  ajax/libs/image-select/1.3/ImageSelect.min.css
  ajax/libs/image-select/1.3/ImageSelect.min.css.map
  ajax/libs/image-select/1.4/ImageSelect.css
  ajax/libs/image-select/1.4/ImageSelect.jquery.js
  ajax/libs/image-select/1.4/ImageSelect.jquery.min.js
  ajax/libs/image-select/1.4/ImageSelect.jquery.min.js.map
  ajax/libs/image-select/1.4/ImageSelect.min.css
  ajax/libs/image-select/1.4/ImageSelect.min.css.map
  ajax/libs/image-select/1.5/ImageSelect.css
  ajax/libs/image-select/1.5/ImageSelect.jquery.js
  ajax/libs/image-select/1.5/ImageSelect.jquery.min.js
  ajax/libs/image-select/1.5/ImageSelect.jquery.min.js.map
  ajax/libs/image-select/1.5/ImageSelect.min.css
  ajax/libs/image-select/1.5/ImageSelect.min.css.map
  ajax/libs/image-select/2.0/Flat.css
  ajax/libs/image-select/2.0/Flat.min.css
  ajax/libs/image-select/2.0/Flat.min.css.map
  ajax/libs/image-select/2.0/ImageSelect.css
  ajax/libs/image-select/2.0/ImageSelect.jquery.js
  ajax/libs/image-select/2.0/ImageSelect.jquery.min.js
  ajax/libs/image-select/2.0/ImageSelect.jquery.min.js.map
  ajax/libs/image-select/2.0/ImageSelect.min.css
  ajax/libs/image-select/2.0/ImageSelect.min.css.map
  ajax/libs/image-select/package.json
Labels: in progress

#11213 [New] Add jsfx@1.2.0 w/ npm auto-update
  ajax/libs/jsfx/1.1.0/jsfx.js
  ajax/libs/jsfx/1.1.0/jsfx.min.js
  ajax/libs/jsfx/1.1.0/jsfx.min.js.map
  ajax/libs/jsfx/1.2.0/jsfx.js
  ajax/libs/jsfx/1.2.0/jsfx.min.js
  ajax/libs/jsfx/1.2.0/jsfx.min.js.map
  ajax/libs/jsfx/package.json
Labels: :warning: PR wait for fixing, in progress

#11821 Add vexflow@1.2.84 w/ npm auto-update
  ajax/libs/vexflow/1.2.11/vexflow-debug.js
  ajax/libs/vexflow/1.2.11/vexflow-min.js
  ajax/libs/vexflow/1.2.11/vexflow-min.js.map
  ajax/libs/vexflow/1.2.12/vexflow-debug.js
  ajax/libs/vexflow/1.2.12/vexflow-min.js
  ajax/libs/vexflow/1.2.12/vexflow-min.js.map
  ajax/libs/vexflow/1.2.14/vexflow-debug.js
  ajax/libs/vexflow/1.2.14/vexflow-min.js
  ajax/libs/vexflow/1.2.14/vexflow-min.js.map
  ajax/libs/vexflow/1.2.84/vexflow-debug.js
  ajax/libs/vexflow/1.2.84/vexflow-debug.js.map
  ajax/libs/vexflow/1.2.84/vexflow-legacy-debug.js
  ajax/libs/vexflow/1.2.84/vexflow-legacy-debug.js.map
  ajax/libs/vexflow/1.2.84/vexflow-legacy-min.js
  ajax/libs/vexflow/1.2.84/vexflow-legacy-min.js.map
  ajax/libs/vexflow/1.2.84/vexflow-min.js
  ajax/libs/vexflow/1.2.84/vexflow-min.js.map
  ajax/libs/vexflow/package.json
Labels: :rotating_light: High Priority, :warning: PR wait for fixing, in progress

#12167 Add jQueryFormStyler@2.0.2 w/ git auto-update
  ajax/libs/jQueryFormStyler/2.0.1/jquery.formstyler.css
  ajax/libs/jQueryFormStyler/2.0.1/jquery.formstyler.js
  ajax/libs/jQueryFormStyler/2.0.1/jquery.formstyler.min.css
  ajax/libs/jQueryFormStyler/2.0.1/jquery.formstyler.min.js
  ajax/libs/jQueryFormStyler/2.0.1/jquery.formstyler.theme.css
  ajax/libs/jQueryFormStyler/2.0.1/jquery.formstyler.theme.min.css
  ajax/libs/jQueryFormStyler/2.0.2/jquery.formstyler.css
  ajax/libs/jQueryFormStyler/2.0.2/jquery.formstyler.js
  ajax/libs/jQueryFormStyler/2.0.2/jquery.formstyler.min.css
  ajax/libs/jQueryFormStyler/2.0.2/jquery.formstyler.min.js
  ajax/libs/jQueryFormStyler/2.0.2/jquery.formstyler.theme.css
  ajax/libs/jQueryFormStyler/2.0.2/jquery.formstyler.theme.min.css
  ajax/libs/jQueryFormStyler/package.json
Labels: in progress

#12784 Update auto update config from git to npm of videojs-ima lib
  ajax/libs/videojs-ima/1.5.1/videojs.ima.css
  ajax/libs/videojs-ima/1.5.1/videojs.ima.js
  ajax/libs/videojs-ima/1.5.1/videojs.ima.min.css
  ajax/libs/videojs-ima/1.5.1/videojs.ima.min.css.map
  ajax/libs/videojs-ima/1.5.1/videojs.ima.min.js
  ajax/libs/videojs-ima/package.json
Labels: :rotating_light: High Priority, in progress

#12082 [New] Add webtorrent-component w/ npm auto-update via single package.json
  ajax/libs/webtorrent-component/package.json
Labels: :warning: PR wait for fixing, in progress

#12304 [New] Add coverflow w/ git auto-update via single package.json
  ajax/libs/coverflow/package.json
Labels: :warning: PR wait for fixing, in progress
