Repository cdnjs/cdnjs, pull requests merged in 2018-05, with the labels that each got.

#11899 [New] Add ng-browser-info w/ git auto-update via single package.json
  ajax/libs/ng-browser-info/package.json
Labels: in progress

#12538 [New] Add modern-normalize w/ git auto-update via single package.json
  ajax/libs/modern-normalize/package.json
Labels: in progress

#12654 [New] Add Vue2Leaflet@1.0.1 w/ git auto-update
  ajax/libs/Vue2Leaflet/1.0.1/vue2-leaflet.js
  ajax/libs/Vue2Leaflet/1.0.1/vue2-leaflet.min.js
  ajax/libs/Vue2Leaflet/1.0.1/vue2-leaflet.min.js.map
  ajax/libs/Vue2Leaflet/package.json
Labels: :rotating_light: High Priority, in progress

#11081 Manually add bootstrap-timepicker missing versions & update metadata
  ajax/libs/bootstrap-timepicker/0.1.1/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.1.1/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.1.1/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.1.1/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.0/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.0/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.0/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.0/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.1/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.1/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.1/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.1/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.2/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.2/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.2/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.2/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.3/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.3/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.3/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.3/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.4/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.4/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.4/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.4/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.5/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.5/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.5/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.5/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/0.2.6/css/bootstrap-timepicker.css
  ajax/libs/bootstrap-timepicker/0.2.6/css/bootstrap-timepicker.min.css
  ajax/libs/bootstrap-timepicker/0.2.6/js/bootstrap-timepicker.js
  ajax/libs/bootstrap-timepicker/0.2.6/js/bootstrap-timepicker.min.js
  ajax/libs/bootstrap-timepicker/package.json
Labels: :rotating_light: High Priority, :warning: PR wait for fixing, in progress

#12771 [Author] Update auto-update config of elfinder
  ajax/libs/elfinder/package.json
Labels: in progress

#12357 [New] Add jquery-rss@3.3.0 w/ git auto-update
  ajax/libs/jquery-rss/3.3.0/jquery.rss.js
  ajax/libs/jquery-rss/3.3.0/jquery.rss.min.js
  ajax/libs/jquery-rss/package.json
Labels: :warning: PR wait for fixing, in progress

#12335 Add PreloadJS missing versions
  ajax/libs/PreloadJS/0.1.0/preloadjs.min.js
  ajax/libs/PreloadJS/0.2.0/preloadjs.min.js
  ajax/libs/PreloadJS/0.3.0/preloadjs.min.js
  ajax/libs/PreloadJS/0.6.0/preloadjs.js
  ajax/libs/PreloadJS/0.6.1/preloadjs.js
  ajax/libs/PreloadJS/0.6.1/preloadjs.min.js
  ajax/libs/PreloadJS/0.6.2/preloadjs.js
  ajax/libs/PreloadJS/0.6.2/preloadjs.min.js
Labels: :warning: PR wait for fixing, in progress

#12233 [New] Add quasar-framework@0.15.10 w/ npm auto-update
  ajax/libs/quasar-framework/0.15.10/i18n.ar.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.bg.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.ca.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.de.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.el.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.en-uk.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.en-us.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.es.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.fa-ir.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.fr.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.he.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.hr.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.id.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.it.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.ja.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.ko-kr.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.lu.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.lv.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.nb-no.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.nl.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.pl.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.pt-br.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.pt.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.ro.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.rs.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.ru.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.sk.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.sl.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.sv.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.th.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.tr.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.uk.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.vi.umd.min.js
  ajax/libs/quasar-framework/0.15.10/i18n.zh-hans.umd.min.js
  ajax/libs/quasar-framework/0.15.10/icons.fontawesome-pro.umd.min.js
  ajax/libs/quasar-framework/0.15.10/icons.fontawesome.umd.min.js
  ajax/libs/quasar-framework/0.15.10/icons.ionicons.umd.min.js
  ajax/libs/quasar-framework/0.15.10/icons.material-icons.umd.min.js
  ajax/libs/quasar-framework/0.15.10/icons.mdi.umd.min.js
  ajax/libs/quasar-framework/0.15.10/quasar.ie.polyfills.umd.min.js
  ajax/libs/quasar-framework/0.15.10/quasar.ios.css
  ajax/libs/quasar-framework/0.15.10/quasar.ios.min.css
  ajax/libs/quasar-framework/0.15.10/quasar.ios.rtl.css
  ajax/libs/quasar-framework/0.15.10/quasar.ios.rtl.min.css
  ajax/libs/quasar-framework/0.15.10/quasar.ios.umd.js
  ajax/libs/quasar-framework/0.15.10/quasar.ios.umd.min.js
  ajax/libs/quasar-framework/0.15.10/quasar.mat.css
  ajax/libs/quasar-framework/0.15.10/quasar.mat.min.css
  ajax/libs/quasar-framework/0.15.10/quasar.mat.rtl.css
  ajax/libs/quasar-framework/0.15.10/quasar.mat.rtl.min.css
  ajax/libs/quasar-framework/0.15.10/quasar.mat.umd.js
  ajax/libs/quasar-framework/0.15.10/quasar.mat.umd.min.js
  ajax/libs/quasar-framework/package.json
Labels: in progress

#12667 [New] Add input-autogrow v1.1.0 with git auto-update
  ajax/libs/input-autogrow/1.1.0/input-autogrow.js
  ajax/libs/input-autogrow/1.1.0/input-autogrow.min.js
  ajax/libs/input-autogrow/package.json
Labels: in progress

#12738 [New] [Author] Add rsuite@3.0.2 w/ npm auto-update
  ajax/libs/rsuite/3.0.2/rsuite.js
  ajax/libs/rsuite/3.0.2/rsuite.js.map
  ajax/libs/rsuite/3.0.2/rsuite.min.js
  ajax/libs/rsuite/3.0.2/rsuite.min.js.map
  ajax/libs/rsuite/3.0.2/styles/fonts/rsuite-icon-font.eot
  ajax/libs/rsuite/3.0.2/styles/fonts/rsuite-icon-font.svg
  ajax/libs/rsuite/3.0.2/styles/fonts/rsuite-icon-font.ttf
  ajax/libs/rsuite/3.0.2/styles/fonts/rsuite-icon-font.woff
  ajax/libs/rsuite/3.0.2/styles/rsuite.css
  ajax/libs/rsuite/3.0.2/styles/rsuite.css.map
  ajax/libs/rsuite/3.0.2/styles/rsuite.min.css
  ajax/libs/rsuite/3.0.2/styles/rsuite.min.css.map
  ajax/libs/rsuite/package.json
Labels: in progress

#12370 [New] Add recharts w/ npm auto-update
  ajax/libs/recharts/0.2.0/chart.js
  ajax/libs/recharts/0.2.0/chart.min.js
  ajax/libs/recharts/0.2.1/chart.js
  ajax/libs/recharts/0.2.1/chart.min.js
  ajax/libs/recharts/0.2.2/chart.js
  ajax/libs/recharts/0.2.2/chart.min.js
  ajax/libs/recharts/0.2.3/chart.js
  ajax/libs/recharts/0.2.3/chart.min.js
  ajax/libs/recharts/0.22.4/Recharts.js
  ajax/libs/recharts/0.22.4/Recharts.min.js
  ajax/libs/recharts/0.3.0/chart.js
  ajax/libs/recharts/0.3.0/chart.min.js
  ajax/libs/recharts/0.3.1/chart.js
  ajax/libs/recharts/0.3.1/chart.min.js
  ajax/libs/recharts/0.3.2/chart.js
  ajax/libs/recharts/0.3.2/chart.min.js
  ajax/libs/recharts/0.3.3/chart.js
  ajax/libs/recharts/0.3.3/chart.min.js
  ajax/libs/recharts/0.3.4/chart.js
  ajax/libs/recharts/0.3.4/chart.min.js
  ajax/libs/recharts/0.3.5/chart.js
  ajax/libs/recharts/0.3.5/chart.min.js
  ajax/libs/recharts/0.3.6/chart.js
  ajax/libs/recharts/0.3.6/chart.min.js
  ajax/libs/recharts/0.3.7/chart.js
  ajax/libs/recharts/0.3.7/chart.min.js
  ajax/libs/recharts/package.json
Labels: in progress

#12664 Add overlayscrollbars w/ npm auto-update via single package.json
  ajax/libs/overlayscrollbars/package.json
Labels: in progress

#10446 [New] Add v-mask@1.3.2 w/ git auto-update
  .gitignore
  ajax/libs/v-mask/1.3.2/v-mask.js
  ajax/libs/v-mask/1.3.2/v-mask.min.js
  ajax/libs/v-mask/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress
