Repository cdnjs/cdnjs, pull requests merged in 2020-03, with the labels that each got.

#9723 add license of webicons, cc #5500
  ajax/libs/webicons/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress

#12260 [New] Add logdown.js w/ npm auto-update
  ajax/libs/logdown/package.json
Labels: in progress

#12640 Update cryptico library license property in package.json
  ajax/libs/cryptico/package.json
Labels: in progress

#12742 Add fontIconPicker /w git auto-update
  ajax/libs/fonticonpicker/package.json
Labels: in progress

#13699 Add bounce.js w/ npm auto-update via single package.json
  ajax/libs/bounce.js/package.json
Labels: :rotating_light: High Priority, in progress

#12153 [New] Add angular-material-calendar w/ git auto-update
  ajax/libs/angular-material-calendar/package.json
Labels: in progress

#12161 Add iphone-inline-video w/ npm auto-update
  ajax/libs/iphone-inline-video/package.json
Labels: in progress

#12207 [New] Add openshare w/ git auto-update
  ajax/libs/openshare/package.json
Labels: in progress

#12392 [New] Add Rpg-Awesome w/ git auto-update via single package.json
  ajax/libs/rpg-awesome/package.json
Labels: in progress

#12422 [New] Add videojs-background w/ npm auto-update
  ajax/libs/videojs-background/package.json
Labels: in progress

#12919 Add firebase@5.4.0 w/ npm auto-aupdate
  .gitignore
  ajax/libs/firebase/package.json
Labels: in progress

#12941 Add print-js w/ npm auto-aupdate
  ajax/libs/print-js/package.json
Labels: in progress

#12162 [New] Add geomicons-open w/ npm auto-update
  ajax/libs/geomicons-open/package.json
Labels: in progress

#11873 [New] Add ammaps w/ git auto-update and update/enrich package.json
  ajax/libs/ammaps/package.json
Labels: in progress

#12609 Update polyglot library properties and auto-update config in package.json
  ajax/libs/polyglot/package.json
Labels: in progress

#12314 Add bootstrap-vue@1.3.0 w/ npm auto-update
  ajax/libs/bootstrap-vue/package.json
Labels: :rotating_light: High Priority, in progress

#12328 [New] Add unistore@3.0.3 w/ npm auto-update
  ajax/libs/unistore/package.json
Labels: :warning: PR wait for fixing, in progress

#12351 Update auto-update config of store.js
  ajax/libs/store.js/package.json
Labels: :arrows_counterclockwise: Wait for response, :rotating_light: High Priority, in progress

#12329 Update blissfuljs homepage & add blissfuljs@1.0.5 w/ npm auto-update
  ajax/libs/blissfuljs/package.json
Labels: :rotating_light: High Priority, in progress

#12473 [New] Add maptalks@0.37.0 w/ npm auto-update
  ajax/libs/maptalks/package.json
Labels: :rotating_light: High Priority, in progress

#12628 [New] Add colresizable w/ git auto-update
  .gitignore
  ajax/libs/colresizable/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress

#13172 [New] Add outdated-browser-rework.js with autoupdate via NPM
  ajax/libs/outdated-browser-rework/package.json
Labels: in progress

#13020 Add parsimmon w/ npm auto-update via single package.json
  ajax/libs/parsimmon/package.json
Labels: in progress

#12962 [New][Author] Add logline w/ npm auto-update via single package.json
  ajax/libs/logline/package.json
Labels: in progress

#12356 [New] Add query-string@5.0.1 w/ git auto-update
  ajax/libs/query-string/package.json
Labels: in progress

#12430 [New] Add turndown@4.0.1 w/ npm auto-update
  ajax/libs/turndown/package.json
Labels: :rotating_light: High Priority, in progress

#12418 [New] Add venn.js w/ npm auto-update via single package.json
  ajax/libs/venn.js/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress

#12887 [author] Update simple-icons package.json
  ajax/libs/simple-icons/package.json
Labels: in progress

#13192 [author] Update country-region-dropdown-menu
  ajax/libs/country-region-dropdown-menu/package.json
Labels: in progress

#13449 Change .js file location for tween.js
  ajax/libs/tween.js/package.json
Labels: :arrows_counterclockwise: Wait for response

#12847 Update emojione auto-update pattern with v3.1.6 and metadata
  ajax/libs/emojione/package.json
Labels: :arrows_counterclockwise: Wait for response, :rotating_light: High Priority, in progress
