Repository cdnjs/cdnjs, pull requests merged in 2020-02, with the labels that each got.

#13495 Updated p5.js description & keywords
  ajax/libs/p5.js/package.json
Labels: :arrows_counterclockwise: Wait for response

#13052 Add between.js w/ npm auto-update via single package.json
  ajax/libs/between.js/package.json
Labels: in progress

#12327 Update popmotion auto-update config
  ajax/libs/popmotion/package.json
Labels: :rotating_light: High Priority, in progress

#11990 Update MIT license & repo library dplayer
  ajax/libs/dplayer/package.json
Labels: in progress

#12025 Add web3 via single package.json w/ npm auto-update
  ajax/libs/web3/package.json
Labels: in progress

#9745 Add blueprintjs-core via single package.json w/ npm auto-update
  ajax/libs/blueprintjs-core/package.json
Labels: :arrows_counterclockwise: Wait for response, in progress

#11926 Add webvr-polyfil via single package.json w/ npm auto-update
  .gitignore
  ajax/libs/webvr-polyfill/package.json
Labels: in progress

#12343 Add vast-client via single package.json w/ npm auto-update
  ajax/libs/vast-client/package.json
Labels: :warning: PR wait for fixing, in progress

#11680 Add ui.multiselect via single package.json w/ git auto-update
  ajax/libs/ui.multiselect/package.json
Labels: in progress
